"""ScheduledTask data model and repository with Memory implementation."""

from __future__ import annotations

import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from nanoclaw.scheduler.cron import is_due


@dataclass
class ScheduledTask:
    """A user-defined cron task.

    The ``schedule`` is a 5-field cron expression.
    ``id`` is auto-generated by the repository (``sched_*`` prefix).
    """

    description: str
    prompt: str
    schedule: str
    user_id: str = "default"
    enabled: bool = True
    id: str = ""
    created_at: float = field(default_factory=time.time)
    last_run: str | None = None  # ISO 8601
    agent_id: str | None = None  # Reserved
    session_id: str | None = None  # Reserved


class ScheduledTaskRepo(ABC):
    """Abstract repository for scheduled tasks (Mock-and-Swap)."""

    @abstractmethod
    async def create(self, task: ScheduledTask) -> ScheduledTask:
        """Persist a new task and return it with a generated ``id``."""

    @abstractmethod
    async def get_due_tasks(self) -> list[ScheduledTask]:
        """Return all tasks whose cron schedule is due right now."""

    @abstractmethod
    async def update_last_run(self, task_id: str, timestamp: str) -> None:
        """Update ``last_run`` after successful execution."""

    @abstractmethod
    async def list_all(self) -> list[ScheduledTask]:
        """Return all tasks (for TUI display)."""

    @abstractmethod
    async def get(self, task_id: str) -> ScheduledTask | None:
        """Get a single task by ID."""

    @abstractmethod
    async def delete(self, task_id: str) -> None:
        """Delete a task by ID."""

    @abstractmethod
    async def update(self, task_id: str, updates: dict[str, Any]) -> ScheduledTask | None:
        """Partial update (e.g. ``{"enabled": False}``). Returns updated task."""


class MemoryScheduledTaskRepo(ScheduledTaskRepo):
    """In-process dict-based implementation."""

    def __init__(self) -> None:
        self._tasks: dict[str, ScheduledTask] = {}
        self._counter = 0

    async def create(self, task: ScheduledTask) -> ScheduledTask:
        self._counter += 1
        task.id = f"sched_{self._counter:04d}"
        self._tasks[task.id] = task
        return task

    async def get_due_tasks(self) -> list[ScheduledTask]:
        now = datetime.now()
        return [
            t
            for t in self._tasks.values()
            if t.enabled and is_due(t.schedule, t.last_run, now)
        ]

    async def update_last_run(self, task_id: str, timestamp: str) -> None:
        task = self._tasks.get(task_id)
        if task is not None:
            task.last_run = timestamp

    async def list_all(self) -> list[ScheduledTask]:
        return list(self._tasks.values())

    async def get(self, task_id: str) -> ScheduledTask | None:
        return self._tasks.get(task_id)

    async def delete(self, task_id: str) -> None:
        self._tasks.pop(task_id, None)

    async def update(self, task_id: str, updates: dict[str, Any]) -> ScheduledTask | None:
        task = self._tasks.get(task_id)
        if task is None:
            return None
        for key, value in updates.items():
            if hasattr(task, key):
                setattr(task, key, value)
        return task
# Phase 5: PgScheduledTaskRepo moved to scheduler/pg_repo.py
